// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewAnnotationStore creates a new instance of AnnotationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnotationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnotationStore {
	mock := &AnnotationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AnnotationStore is an autogenerated mock type for the AnnotationStore type
type AnnotationStore struct {
	mock.Mock
}

type AnnotationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AnnotationStore) EXPECT() *AnnotationStore_Expecter {
	return &AnnotationStore_Expecter{mock: &_m.Mock}
}

// GetByUserAndNode provides a mock function for the type AnnotationStore
func (_mock *AnnotationStore) GetByUserAndNode(ctx context.Context, userID string, nodeID string) (*models.UserAnnotation, error) {
	ret := _mock.Called(ctx, userID, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndNode")
	}

	var r0 *models.UserAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.UserAnnotation, error)); ok {
		return returnFunc(ctx, userID, nodeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.UserAnnotation); ok {
		r0 = returnFunc(ctx, userID, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, nodeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AnnotationStore_GetByUserAndNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndNode'
type AnnotationStore_GetByUserAndNode_Call struct {
	*mock.Call
}

// GetByUserAndNode is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - nodeID string
func (_e *AnnotationStore_Expecter) GetByUserAndNode(ctx interface{}, userID interface{}, nodeID interface{}) *AnnotationStore_GetByUserAndNode_Call {
	return &AnnotationStore_GetByUserAndNode_Call{Call: _e.mock.On("GetByUserAndNode", ctx, userID, nodeID)}
}

func (_c *AnnotationStore_GetByUserAndNode_Call) Run(run func(ctx context.Context, userID string, nodeID string)) *AnnotationStore_GetByUserAndNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AnnotationStore_GetByUserAndNode_Call) Return(userAnnotation *models.UserAnnotation, err error) *AnnotationStore_GetByUserAndNode_Call {
	_c.Call.Return(userAnnotation, err)
	return _c
}

func (_c *AnnotationStore_GetByUserAndNode_Call) RunAndReturn(run func(ctx context.Context, userID string, nodeID string) (*models.UserAnnotation, error)) *AnnotationStore_GetByUserAndNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type AnnotationStore
func (_mock *AnnotationStore) GetByUserID(ctx context.Context, userID string) ([]models.UserAnnotation, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []models.UserAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.UserAnnotation, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.UserAnnotation); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AnnotationStore_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type AnnotationStore_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AnnotationStore_Expecter) GetByUserID(ctx interface{}, userID interface{}) *AnnotationStore_GetByUserID_Call {
	return &AnnotationStore_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *AnnotationStore_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *AnnotationStore_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AnnotationStore_GetByUserID_Call) Return(userAnnotations []models.UserAnnotation, err error) *AnnotationStore_GetByUserID_Call {
	_c.Call.Return(userAnnotations, err)
	return _c
}

func (_c *AnnotationStore_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]models.UserAnnotation, error)) *AnnotationStore_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type AnnotationStore
func (_mock *AnnotationStore) Upsert(ctx context.Context, userID string, nodeID string, stance string, notes string) error {
	ret := _mock.Called(ctx, userID, nodeID, stance, notes)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, nodeID, stance, notes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AnnotationStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type AnnotationStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - nodeID string
//   - stance string
//   - notes string
func (_e *AnnotationStore_Expecter) Upsert(ctx interface{}, userID interface{}, nodeID interface{}, stance interface{}, notes interface{}) *AnnotationStore_Upsert_Call {
	return &AnnotationStore_Upsert_Call{Call: _e.mock.On("Upsert", ctx, userID, nodeID, stance, notes)}
}

func (_c *AnnotationStore_Upsert_Call) Run(run func(ctx context.Context, userID string, nodeID string, stance string, notes string)) *AnnotationStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AnnotationStore_Upsert_Call) Return(err error) *AnnotationStore_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AnnotationStore_Upsert_Call) RunAndReturn(run func(ctx context.Context, userID string, nodeID string, stance string, notes string) error) *AnnotationStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
