// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewEdgeStore creates a new instance of EdgeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEdgeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EdgeStore {
	mock := &EdgeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EdgeStore is an autogenerated mock type for the EdgeStore type
type EdgeStore struct {
	mock.Mock
}

type EdgeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EdgeStore) EXPECT() *EdgeStore_Expecter {
	return &EdgeStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type EdgeStore
func (_mock *EdgeStore) Create(ctx context.Context, id string, edgeType models.EdgeType, sourceID string, targetID string, description string, sourceTextID string) (*models.Edge, error) {
	ret := _mock.Called(ctx, id, edgeType, sourceID, targetID, description, sourceTextID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Edge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.EdgeType, string, string, string, string) (*models.Edge, error)); ok {
		return returnFunc(ctx, id, edgeType, sourceID, targetID, description, sourceTextID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.EdgeType, string, string, string, string) *models.Edge); ok {
		r0 = returnFunc(ctx, id, edgeType, sourceID, targetID, description, sourceTextID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Edge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.EdgeType, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, edgeType, sourceID, targetID, description, sourceTextID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EdgeStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EdgeStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - edgeType models.EdgeType
//   - sourceID string
//   - targetID string
//   - description string
//   - sourceTextID string
func (_e *EdgeStore_Expecter) Create(ctx interface{}, id interface{}, edgeType interface{}, sourceID interface{}, targetID interface{}, description interface{}, sourceTextID interface{}) *EdgeStore_Create_Call {
	return &EdgeStore_Create_Call{Call: _e.mock.On("Create", ctx, id, edgeType, sourceID, targetID, description, sourceTextID)}
}

func (_c *EdgeStore_Create_Call) Run(run func(ctx context.Context, id string, edgeType models.EdgeType, sourceID string, targetID string, description string, sourceTextID string)) *EdgeStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.EdgeType
		if args[2] != nil {
			arg2 = args[2].(models.EdgeType)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *EdgeStore_Create_Call) Return(edge *models.Edge, err error) *EdgeStore_Create_Call {
	_c.Call.Return(edge, err)
	return _c
}

func (_c *EdgeStore_Create_Call) RunAndReturn(run func(ctx context.Context, id string, edgeType models.EdgeType, sourceID string, targetID string, description string, sourceTextID string) (*models.Edge, error)) *EdgeStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type EdgeStore
func (_mock *EdgeStore) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EdgeStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EdgeStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *EdgeStore_Expecter) Delete(ctx interface{}, id interface{}) *EdgeStore_Delete_Call {
	return &EdgeStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *EdgeStore_Delete_Call) Run(run func(ctx context.Context, id string)) *EdgeStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EdgeStore_Delete_Call) Return(err error) *EdgeStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EdgeStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *EdgeStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type EdgeStore
func (_mock *EdgeStore) Update(ctx context.Context, id string, update models.EdgeUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.EdgeUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EdgeStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EdgeStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update models.EdgeUpdate
func (_e *EdgeStore_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *EdgeStore_Update_Call {
	return &EdgeStore_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *EdgeStore_Update_Call) Run(run func(ctx context.Context, id string, update models.EdgeUpdate)) *EdgeStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.EdgeUpdate
		if args[2] != nil {
			arg2 = args[2].(models.EdgeUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EdgeStore_Update_Call) Return(err error) *EdgeStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EdgeStore_Update_Call) RunAndReturn(run func(ctx context.Context, id string, update models.EdgeUpdate) error) *EdgeStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
