// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/response"
	mock "github.com/stretchr/testify/mock"
)

// NewGraphStore creates a new instance of GraphStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGraphStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *GraphStore {
	mock := &GraphStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GraphStore is an autogenerated mock type for the GraphStore type
type GraphStore struct {
	mock.Mock
}

type GraphStore_Expecter struct {
	mock *mock.Mock
}

func (_m *GraphStore) EXPECT() *GraphStore_Expecter {
	return &GraphStore_Expecter{mock: &_m.Mock}
}

// GetFullGraph provides a mock function for the type GraphStore
func (_mock *GraphStore) GetFullGraph(ctx context.Context) (*response.GraphData, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFullGraph")
	}

	var r0 *response.GraphData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*response.GraphData, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *response.GraphData); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GraphStore_GetFullGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullGraph'
type GraphStore_GetFullGraph_Call struct {
	*mock.Call
}

// GetFullGraph is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GraphStore_Expecter) GetFullGraph(ctx interface{}) *GraphStore_GetFullGraph_Call {
	return &GraphStore_GetFullGraph_Call{Call: _e.mock.On("GetFullGraph", ctx)}
}

func (_c *GraphStore_GetFullGraph_Call) Run(run func(ctx context.Context)) *GraphStore_GetFullGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GraphStore_GetFullGraph_Call) Return(graphData *response.GraphData, err error) *GraphStore_GetFullGraph_Call {
	_c.Call.Return(graphData, err)
	return _c
}

func (_c *GraphStore_GetFullGraph_Call) RunAndReturn(run func(ctx context.Context) (*response.GraphData, error)) *GraphStore_GetFullGraph_Call {
	_c.Call.Return(run)
	return _c
}

// GetPath provides a mock function for the type GraphStore
func (_mock *GraphStore) GetPath(ctx context.Context, fromID string, toID string) (*response.GraphData, error) {
	ret := _mock.Called(ctx, fromID, toID)

	if len(ret) == 0 {
		panic("no return value specified for GetPath")
	}

	var r0 *response.GraphData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.GraphData, error)); ok {
		return returnFunc(ctx, fromID, toID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.GraphData); ok {
		r0 = returnFunc(ctx, fromID, toID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, fromID, toID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GraphStore_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type GraphStore_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID string
//   - toID string
func (_e *GraphStore_Expecter) GetPath(ctx interface{}, fromID interface{}, toID interface{}) *GraphStore_GetPath_Call {
	return &GraphStore_GetPath_Call{Call: _e.mock.On("GetPath", ctx, fromID, toID)}
}

func (_c *GraphStore_GetPath_Call) Run(run func(ctx context.Context, fromID string, toID string)) *GraphStore_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GraphStore_GetPath_Call) Return(graphData *response.GraphData, err error) *GraphStore_GetPath_Call {
	_c.Call.Return(graphData, err)
	return _c
}

func (_c *GraphStore_GetPath_Call) RunAndReturn(run func(ctx context.Context, fromID string, toID string) (*response.GraphData, error)) *GraphStore_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubgraph provides a mock function for the type GraphStore
func (_mock *GraphStore) GetSubgraph(ctx context.Context, textID string) (*response.GraphData, error) {
	ret := _mock.Called(ctx, textID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubgraph")
	}

	var r0 *response.GraphData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*response.GraphData, error)); ok {
		return returnFunc(ctx, textID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *response.GraphData); ok {
		r0 = returnFunc(ctx, textID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, textID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GraphStore_GetSubgraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubgraph'
type GraphStore_GetSubgraph_Call struct {
	*mock.Call
}

// GetSubgraph is a helper method to define mock.On call
//   - ctx context.Context
//   - textID string
func (_e *GraphStore_Expecter) GetSubgraph(ctx interface{}, textID interface{}) *GraphStore_GetSubgraph_Call {
	return &GraphStore_GetSubgraph_Call{Call: _e.mock.On("GetSubgraph", ctx, textID)}
}

func (_c *GraphStore_GetSubgraph_Call) Run(run func(ctx context.Context, textID string)) *GraphStore_GetSubgraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GraphStore_GetSubgraph_Call) Return(graphData *response.GraphData, err error) *GraphStore_GetSubgraph_Call {
	_c.Call.Return(graphData, err)
	return _c
}

func (_c *GraphStore_GetSubgraph_Call) RunAndReturn(run func(ctx context.Context, textID string) (*response.GraphData, error)) *GraphStore_GetSubgraph_Call {
	_c.Call.Return(run)
	return _c
}
