// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/models"
	"github.com/bonjuruu/aporia/internal/response"
	mock "github.com/stretchr/testify/mock"
)

// NewNodeStore creates a new instance of NodeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeStore {
	mock := &NodeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NodeStore is an autogenerated mock type for the NodeStore type
type NodeStore struct {
	mock.Mock
}

type NodeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeStore) EXPECT() *NodeStore_Expecter {
	return &NodeStore_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type NodeStore
func (_mock *NodeStore) Count(ctx context.Context) (*int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *int64); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type NodeStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeStore_Expecter) Count(ctx interface{}) *NodeStore_Count_Call {
	return &NodeStore_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *NodeStore_Count_Call) Run(run func(ctx context.Context)) *NodeStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeStore_Count_Call) Return(n *int64, err error) *NodeStore_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *NodeStore_Count_Call) RunAndReturn(run func(ctx context.Context) (*int64, error)) *NodeStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClaim provides a mock function for the type NodeStore
func (_mock *NodeStore) CreateClaim(ctx context.Context, claim models.Claim) (*response.GraphNode, error) {
	ret := _mock.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for CreateClaim")
	}

	var r0 *response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Claim) (*response.GraphNode, error)); ok {
		return returnFunc(ctx, claim)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Claim) *response.GraphNode); ok {
		r0 = returnFunc(ctx, claim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Claim) error); ok {
		r1 = returnFunc(ctx, claim)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_CreateClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClaim'
type NodeStore_CreateClaim_Call struct {
	*mock.Call
}

// CreateClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - claim models.Claim
func (_e *NodeStore_Expecter) CreateClaim(ctx interface{}, claim interface{}) *NodeStore_CreateClaim_Call {
	return &NodeStore_CreateClaim_Call{Call: _e.mock.On("CreateClaim", ctx, claim)}
}

func (_c *NodeStore_CreateClaim_Call) Run(run func(ctx context.Context, claim models.Claim)) *NodeStore_CreateClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Claim
		if args[1] != nil {
			arg1 = args[1].(models.Claim)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_CreateClaim_Call) Return(graphNode *response.GraphNode, err error) *NodeStore_CreateClaim_Call {
	_c.Call.Return(graphNode, err)
	return _c
}

func (_c *NodeStore_CreateClaim_Call) RunAndReturn(run func(ctx context.Context, claim models.Claim) (*response.GraphNode, error)) *NodeStore_CreateClaim_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConcept provides a mock function for the type NodeStore
func (_mock *NodeStore) CreateConcept(ctx context.Context, concept models.Concept) (*response.GraphNode, error) {
	ret := _mock.Called(ctx, concept)

	if len(ret) == 0 {
		panic("no return value specified for CreateConcept")
	}

	var r0 *response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Concept) (*response.GraphNode, error)); ok {
		return returnFunc(ctx, concept)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Concept) *response.GraphNode); ok {
		r0 = returnFunc(ctx, concept)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Concept) error); ok {
		r1 = returnFunc(ctx, concept)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_CreateConcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConcept'
type NodeStore_CreateConcept_Call struct {
	*mock.Call
}

// CreateConcept is a helper method to define mock.On call
//   - ctx context.Context
//   - concept models.Concept
func (_e *NodeStore_Expecter) CreateConcept(ctx interface{}, concept interface{}) *NodeStore_CreateConcept_Call {
	return &NodeStore_CreateConcept_Call{Call: _e.mock.On("CreateConcept", ctx, concept)}
}

func (_c *NodeStore_CreateConcept_Call) Run(run func(ctx context.Context, concept models.Concept)) *NodeStore_CreateConcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Concept
		if args[1] != nil {
			arg1 = args[1].(models.Concept)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_CreateConcept_Call) Return(graphNode *response.GraphNode, err error) *NodeStore_CreateConcept_Call {
	_c.Call.Return(graphNode, err)
	return _c
}

func (_c *NodeStore_CreateConcept_Call) RunAndReturn(run func(ctx context.Context, concept models.Concept) (*response.GraphNode, error)) *NodeStore_CreateConcept_Call {
	_c.Call.Return(run)
	return _c
}

// CreateText provides a mock function for the type NodeStore
func (_mock *NodeStore) CreateText(ctx context.Context, text models.Text) (*response.GraphNode, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateText")
	}

	var r0 *response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Text) (*response.GraphNode, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Text) *response.GraphNode); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Text) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_CreateText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateText'
type NodeStore_CreateText_Call struct {
	*mock.Call
}

// CreateText is a helper method to define mock.On call
//   - ctx context.Context
//   - text models.Text
func (_e *NodeStore_Expecter) CreateText(ctx interface{}, text interface{}) *NodeStore_CreateText_Call {
	return &NodeStore_CreateText_Call{Call: _e.mock.On("CreateText", ctx, text)}
}

func (_c *NodeStore_CreateText_Call) Run(run func(ctx context.Context, text models.Text)) *NodeStore_CreateText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Text
		if args[1] != nil {
			arg1 = args[1].(models.Text)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_CreateText_Call) Return(graphNode *response.GraphNode, err error) *NodeStore_CreateText_Call {
	_c.Call.Return(graphNode, err)
	return _c
}

func (_c *NodeStore_CreateText_Call) RunAndReturn(run func(ctx context.Context, text models.Text) (*response.GraphNode, error)) *NodeStore_CreateText_Call {
	_c.Call.Return(run)
	return _c
}

// CreateThinker provides a mock function for the type NodeStore
func (_mock *NodeStore) CreateThinker(ctx context.Context, thinker models.Thinker) (*response.GraphNode, error) {
	ret := _mock.Called(ctx, thinker)

	if len(ret) == 0 {
		panic("no return value specified for CreateThinker")
	}

	var r0 *response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Thinker) (*response.GraphNode, error)); ok {
		return returnFunc(ctx, thinker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Thinker) *response.GraphNode); ok {
		r0 = returnFunc(ctx, thinker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Thinker) error); ok {
		r1 = returnFunc(ctx, thinker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_CreateThinker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateThinker'
type NodeStore_CreateThinker_Call struct {
	*mock.Call
}

// CreateThinker is a helper method to define mock.On call
//   - ctx context.Context
//   - thinker models.Thinker
func (_e *NodeStore_Expecter) CreateThinker(ctx interface{}, thinker interface{}) *NodeStore_CreateThinker_Call {
	return &NodeStore_CreateThinker_Call{Call: _e.mock.On("CreateThinker", ctx, thinker)}
}

func (_c *NodeStore_CreateThinker_Call) Run(run func(ctx context.Context, thinker models.Thinker)) *NodeStore_CreateThinker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Thinker
		if args[1] != nil {
			arg1 = args[1].(models.Thinker)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_CreateThinker_Call) Return(graphNode *response.GraphNode, err error) *NodeStore_CreateThinker_Call {
	_c.Call.Return(graphNode, err)
	return _c
}

func (_c *NodeStore_CreateThinker_Call) RunAndReturn(run func(ctx context.Context, thinker models.Thinker) (*response.GraphNode, error)) *NodeStore_CreateThinker_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type NodeStore
func (_mock *NodeStore) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NodeStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NodeStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NodeStore_Expecter) Delete(ctx interface{}, id interface{}) *NodeStore_Delete_Call {
	return &NodeStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *NodeStore_Delete_Call) Run(run func(ctx context.Context, id string)) *NodeStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_Delete_Call) Return(err error) *NodeStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NodeStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *NodeStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type NodeStore
func (_mock *NodeStore) GetAll(ctx context.Context) ([]response.GraphNode, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]response.GraphNode, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []response.GraphNode); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type NodeStore_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeStore_Expecter) GetAll(ctx interface{}) *NodeStore_GetAll_Call {
	return &NodeStore_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *NodeStore_GetAll_Call) Run(run func(ctx context.Context)) *NodeStore_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeStore_GetAll_Call) Return(graphNodes []response.GraphNode, err error) *NodeStore_GetAll_Call {
	_c.Call.Return(graphNodes, err)
	return _c
}

func (_c *NodeStore_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]response.GraphNode, error)) *NodeStore_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type NodeStore
func (_mock *NodeStore) GetByID(ctx context.Context, id string) (*response.NodeDetail, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.NodeDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*response.NodeDetail, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *response.NodeDetail); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.NodeDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type NodeStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NodeStore_Expecter) GetByID(ctx interface{}, id interface{}) *NodeStore_GetByID_Call {
	return &NodeStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *NodeStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *NodeStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_GetByID_Call) Return(nodeDetail *response.NodeDetail, err error) *NodeStore_GetByID_Call {
	_c.Call.Return(nodeDetail, err)
	return _c
}

func (_c *NodeStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*response.NodeDetail, error)) *NodeStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type NodeStore
func (_mock *NodeStore) Search(ctx context.Context, query string) ([]response.GraphNode, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]response.GraphNode, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []response.GraphNode); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NodeStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type NodeStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *NodeStore_Expecter) Search(ctx interface{}, query interface{}) *NodeStore_Search_Call {
	return &NodeStore_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *NodeStore_Search_Call) Run(run func(ctx context.Context, query string)) *NodeStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NodeStore_Search_Call) Return(graphNodes []response.GraphNode, err error) *NodeStore_Search_Call {
	_c.Call.Return(graphNodes, err)
	return _c
}

func (_c *NodeStore_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]response.GraphNode, error)) *NodeStore_Search_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClaim provides a mock function for the type NodeStore
func (_mock *NodeStore) UpdateClaim(ctx context.Context, id string, update models.ClaimUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClaim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ClaimUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NodeStore_UpdateClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClaim'
type NodeStore_UpdateClaim_Call struct {
	*mock.Call
}

// UpdateClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update models.ClaimUpdate
func (_e *NodeStore_Expecter) UpdateClaim(ctx interface{}, id interface{}, update interface{}) *NodeStore_UpdateClaim_Call {
	return &NodeStore_UpdateClaim_Call{Call: _e.mock.On("UpdateClaim", ctx, id, update)}
}

func (_c *NodeStore_UpdateClaim_Call) Run(run func(ctx context.Context, id string, update models.ClaimUpdate)) *NodeStore_UpdateClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ClaimUpdate
		if args[2] != nil {
			arg2 = args[2].(models.ClaimUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NodeStore_UpdateClaim_Call) Return(err error) *NodeStore_UpdateClaim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NodeStore_UpdateClaim_Call) RunAndReturn(run func(ctx context.Context, id string, update models.ClaimUpdate) error) *NodeStore_UpdateClaim_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConcept provides a mock function for the type NodeStore
func (_mock *NodeStore) UpdateConcept(ctx context.Context, id string, update models.ConceptUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConcept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ConceptUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NodeStore_UpdateConcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConcept'
type NodeStore_UpdateConcept_Call struct {
	*mock.Call
}

// UpdateConcept is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update models.ConceptUpdate
func (_e *NodeStore_Expecter) UpdateConcept(ctx interface{}, id interface{}, update interface{}) *NodeStore_UpdateConcept_Call {
	return &NodeStore_UpdateConcept_Call{Call: _e.mock.On("UpdateConcept", ctx, id, update)}
}

func (_c *NodeStore_UpdateConcept_Call) Run(run func(ctx context.Context, id string, update models.ConceptUpdate)) *NodeStore_UpdateConcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ConceptUpdate
		if args[2] != nil {
			arg2 = args[2].(models.ConceptUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NodeStore_UpdateConcept_Call) Return(err error) *NodeStore_UpdateConcept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NodeStore_UpdateConcept_Call) RunAndReturn(run func(ctx context.Context, id string, update models.ConceptUpdate) error) *NodeStore_UpdateConcept_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateText provides a mock function for the type NodeStore
func (_mock *NodeStore) UpdateText(ctx context.Context, id string, update models.TextUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.TextUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NodeStore_UpdateText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateText'
type NodeStore_UpdateText_Call struct {
	*mock.Call
}

// UpdateText is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update models.TextUpdate
func (_e *NodeStore_Expecter) UpdateText(ctx interface{}, id interface{}, update interface{}) *NodeStore_UpdateText_Call {
	return &NodeStore_UpdateText_Call{Call: _e.mock.On("UpdateText", ctx, id, update)}
}

func (_c *NodeStore_UpdateText_Call) Run(run func(ctx context.Context, id string, update models.TextUpdate)) *NodeStore_UpdateText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.TextUpdate
		if args[2] != nil {
			arg2 = args[2].(models.TextUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NodeStore_UpdateText_Call) Return(err error) *NodeStore_UpdateText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NodeStore_UpdateText_Call) RunAndReturn(run func(ctx context.Context, id string, update models.TextUpdate) error) *NodeStore_UpdateText_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateThinker provides a mock function for the type NodeStore
func (_mock *NodeStore) UpdateThinker(ctx context.Context, id string, update models.ThinkerUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThinker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ThinkerUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NodeStore_UpdateThinker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateThinker'
type NodeStore_UpdateThinker_Call struct {
	*mock.Call
}

// UpdateThinker is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update models.ThinkerUpdate
func (_e *NodeStore_Expecter) UpdateThinker(ctx interface{}, id interface{}, update interface{}) *NodeStore_UpdateThinker_Call {
	return &NodeStore_UpdateThinker_Call{Call: _e.mock.On("UpdateThinker", ctx, id, update)}
}

func (_c *NodeStore_UpdateThinker_Call) Run(run func(ctx context.Context, id string, update models.ThinkerUpdate)) *NodeStore_UpdateThinker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ThinkerUpdate
		if args[2] != nil {
			arg2 = args[2].(models.ThinkerUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NodeStore_UpdateThinker_Call) Return(err error) *NodeStore_UpdateThinker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NodeStore_UpdateThinker_Call) RunAndReturn(run func(ctx context.Context, id string, update models.ThinkerUpdate) error) *NodeStore_UpdateThinker_Call {
	_c.Call.Return(run)
	return _c
}
