// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewProgressStore creates a new instance of ProgressStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProgressStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProgressStore {
	mock := &ProgressStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProgressStore is an autogenerated mock type for the ProgressStore type
type ProgressStore struct {
	mock.Mock
}

type ProgressStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ProgressStore) EXPECT() *ProgressStore_Expecter {
	return &ProgressStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type ProgressStore
func (_mock *ProgressStore) Get(ctx context.Context, userID string, textID string) (*models.ReadingProgress, error) {
	ret := _mock.Called(ctx, userID, textID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.ReadingProgress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.ReadingProgress, error)); ok {
		return returnFunc(ctx, userID, textID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.ReadingProgress); ok {
		r0 = returnFunc(ctx, userID, textID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadingProgress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, textID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProgressStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProgressStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - textID string
func (_e *ProgressStore_Expecter) Get(ctx interface{}, userID interface{}, textID interface{}) *ProgressStore_Get_Call {
	return &ProgressStore_Get_Call{Call: _e.mock.On("Get", ctx, userID, textID)}
}

func (_c *ProgressStore_Get_Call) Run(run func(ctx context.Context, userID string, textID string)) *ProgressStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProgressStore_Get_Call) Return(readingProgress *models.ReadingProgress, err error) *ProgressStore_Get_Call {
	_c.Call.Return(readingProgress, err)
	return _c
}

func (_c *ProgressStore_Get_Call) RunAndReturn(run func(ctx context.Context, userID string, textID string) (*models.ReadingProgress, error)) *ProgressStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ProgressStore
func (_mock *ProgressStore) List(ctx context.Context, userID string) ([]*models.ReadingProgress, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.ReadingProgress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.ReadingProgress, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.ReadingProgress); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ReadingProgress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProgressStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProgressStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ProgressStore_Expecter) List(ctx interface{}, userID interface{}) *ProgressStore_List_Call {
	return &ProgressStore_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *ProgressStore_List_Call) Run(run func(ctx context.Context, userID string)) *ProgressStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProgressStore_List_Call) Return(readingProgresss []*models.ReadingProgress, err error) *ProgressStore_List_Call {
	_c.Call.Return(readingProgresss, err)
	return _c
}

func (_c *ProgressStore_List_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*models.ReadingProgress, error)) *ProgressStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type ProgressStore
func (_mock *ProgressStore) Upsert(ctx context.Context, userID string, textID string, chapter string, totalChapters *int, lastReadAt string, sessionNotesJSON string) (*models.ReadingProgress, error) {
	ret := _mock.Called(ctx, userID, textID, chapter, totalChapters, lastReadAt, sessionNotesJSON)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *models.ReadingProgress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *int, string, string) (*models.ReadingProgress, error)); ok {
		return returnFunc(ctx, userID, textID, chapter, totalChapters, lastReadAt, sessionNotesJSON)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *int, string, string) *models.ReadingProgress); ok {
		r0 = returnFunc(ctx, userID, textID, chapter, totalChapters, lastReadAt, sessionNotesJSON)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadingProgress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *int, string, string) error); ok {
		r1 = returnFunc(ctx, userID, textID, chapter, totalChapters, lastReadAt, sessionNotesJSON)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProgressStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type ProgressStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - textID string
//   - chapter string
//   - totalChapters *int
//   - lastReadAt string
//   - sessionNotesJSON string
func (_e *ProgressStore_Expecter) Upsert(ctx interface{}, userID interface{}, textID interface{}, chapter interface{}, totalChapters interface{}, lastReadAt interface{}, sessionNotesJSON interface{}) *ProgressStore_Upsert_Call {
	return &ProgressStore_Upsert_Call{Call: _e.mock.On("Upsert", ctx, userID, textID, chapter, totalChapters, lastReadAt, sessionNotesJSON)}
}

func (_c *ProgressStore_Upsert_Call) Run(run func(ctx context.Context, userID string, textID string, chapter string, totalChapters *int, lastReadAt string, sessionNotesJSON string)) *ProgressStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *ProgressStore_Upsert_Call) Return(readingProgress *models.ReadingProgress, err error) *ProgressStore_Upsert_Call {
	_c.Call.Return(readingProgress, err)
	return _c
}

func (_c *ProgressStore_Upsert_Call) RunAndReturn(run func(ctx context.Context, userID string, textID string, chapter string, totalChapters *int, lastReadAt string, sessionNotesJSON string) (*models.ReadingProgress, error)) *ProgressStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
