// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/models"
	"github.com/bonjuruu/aporia/internal/response"
	mock "github.com/stretchr/testify/mock"
)

// NewQuoteStore creates a new instance of QuoteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuoteStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuoteStore {
	mock := &QuoteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuoteStore is an autogenerated mock type for the QuoteStore type
type QuoteStore struct {
	mock.Mock
}

type QuoteStore_Expecter struct {
	mock *mock.Mock
}

func (_m *QuoteStore) EXPECT() *QuoteStore_Expecter {
	return &QuoteStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type QuoteStore
func (_mock *QuoteStore) Create(ctx context.Context, userID string, quote models.Quote) (*models.Quote, error) {
	ret := _mock.Called(ctx, userID, quote)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Quote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.Quote) (*models.Quote, error)); ok {
		return returnFunc(ctx, userID, quote)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.Quote) *models.Quote); ok {
		r0 = returnFunc(ctx, userID, quote)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Quote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.Quote) error); ok {
		r1 = returnFunc(ctx, userID, quote)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuoteStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type QuoteStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - quote models.Quote
func (_e *QuoteStore_Expecter) Create(ctx interface{}, userID interface{}, quote interface{}) *QuoteStore_Create_Call {
	return &QuoteStore_Create_Call{Call: _e.mock.On("Create", ctx, userID, quote)}
}

func (_c *QuoteStore_Create_Call) Run(run func(ctx context.Context, userID string, quote models.Quote)) *QuoteStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.Quote
		if args[2] != nil {
			arg2 = args[2].(models.Quote)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QuoteStore_Create_Call) Return(quote1 *models.Quote, err error) *QuoteStore_Create_Call {
	_c.Call.Return(quote1, err)
	return _c
}

func (_c *QuoteStore_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, quote models.Quote) (*models.Quote, error)) *QuoteStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type QuoteStore
func (_mock *QuoteStore) Delete(ctx context.Context, userID string, id string) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuoteStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type QuoteStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *QuoteStore_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *QuoteStore_Delete_Call {
	return &QuoteStore_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *QuoteStore_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *QuoteStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QuoteStore_Delete_Call) Return(err error) *QuoteStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuoteStore_Delete_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) error) *QuoteStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type QuoteStore
func (_mock *QuoteStore) ListByUser(ctx context.Context, userID string, textID string) ([]*models.Quote, error) {
	ret := _mock.Called(ctx, userID, textID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*models.Quote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*models.Quote, error)); ok {
		return returnFunc(ctx, userID, textID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*models.Quote); ok {
		r0 = returnFunc(ctx, userID, textID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Quote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, textID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuoteStore_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type QuoteStore_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - textID string
func (_e *QuoteStore_Expecter) ListByUser(ctx interface{}, userID interface{}, textID interface{}) *QuoteStore_ListByUser_Call {
	return &QuoteStore_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, textID)}
}

func (_c *QuoteStore_ListByUser_Call) Run(run func(ctx context.Context, userID string, textID string)) *QuoteStore_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QuoteStore_ListByUser_Call) Return(quotes []*models.Quote, err error) *QuoteStore_ListByUser_Call {
	_c.Call.Return(quotes, err)
	return _c
}

func (_c *QuoteStore_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string, textID string) ([]*models.Quote, error)) *QuoteStore_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Promote provides a mock function for the type QuoteStore
func (_mock *QuoteStore) Promote(ctx context.Context, quoteID string, label string, props map[string]any) (*response.GraphNode, error) {
	ret := _mock.Called(ctx, quoteID, label, props)

	if len(ret) == 0 {
		panic("no return value specified for Promote")
	}

	var r0 *response.GraphNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any) (*response.GraphNode, error)); ok {
		return returnFunc(ctx, quoteID, label, props)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any) *response.GraphNode); ok {
		r0 = returnFunc(ctx, quoteID, label, props)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GraphNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, quoteID, label, props)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuoteStore_Promote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Promote'
type QuoteStore_Promote_Call struct {
	*mock.Call
}

// Promote is a helper method to define mock.On call
//   - ctx context.Context
//   - quoteID string
//   - label string
//   - props map[string]any
func (_e *QuoteStore_Expecter) Promote(ctx interface{}, quoteID interface{}, label interface{}, props interface{}) *QuoteStore_Promote_Call {
	return &QuoteStore_Promote_Call{Call: _e.mock.On("Promote", ctx, quoteID, label, props)}
}

func (_c *QuoteStore_Promote_Call) Run(run func(ctx context.Context, quoteID string, label string, props map[string]any)) *QuoteStore_Promote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *QuoteStore_Promote_Call) Return(graphNode *response.GraphNode, err error) *QuoteStore_Promote_Call {
	_c.Call.Return(graphNode, err)
	return _c
}

func (_c *QuoteStore_Promote_Call) RunAndReturn(run func(ctx context.Context, quoteID string, label string, props map[string]any) (*response.GraphNode, error)) *QuoteStore_Promote_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type QuoteStore
func (_mock *QuoteStore) Update(ctx context.Context, userID string, id string, reaction *string, page *int) error {
	ret := _mock.Called(ctx, userID, id, reaction, page)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *int) error); ok {
		r0 = returnFunc(ctx, userID, id, reaction, page)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuoteStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type QuoteStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - reaction *string
//   - page *int
func (_e *QuoteStore_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, reaction interface{}, page interface{}) *QuoteStore_Update_Call {
	return &QuoteStore_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, reaction, page)}
}

func (_c *QuoteStore_Update_Call) Run(run func(ctx context.Context, userID string, id string, reaction *string, page *int)) *QuoteStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *QuoteStore_Update_Call) Return(err error) *QuoteStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuoteStore_Update_Call) RunAndReturn(run func(ctx context.Context, userID string, id string, reaction *string, page *int) error) *QuoteStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
