// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/bonjuruu/aporia/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUserStore creates a new instance of UserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStore {
	mock := &UserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserStore is an autogenerated mock type for the UserStore type
type UserStore struct {
	mock.Mock
}

type UserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStore) EXPECT() *UserStore_Expecter {
	return &UserStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserStore
func (_mock *UserStore) Create(ctx context.Context, id string, email string, passwordHash string, createdAt string) (*models.User, error) {
	ret := _mock.Called(ctx, id, email, passwordHash, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*models.User, error)); ok {
		return returnFunc(ctx, id, email, passwordHash, createdAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *models.User); ok {
		r0 = returnFunc(ctx, id, email, passwordHash, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, email, passwordHash, createdAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - email string
//   - passwordHash string
//   - createdAt string
func (_e *UserStore_Expecter) Create(ctx interface{}, id interface{}, email interface{}, passwordHash interface{}, createdAt interface{}) *UserStore_Create_Call {
	return &UserStore_Create_Call{Call: _e.mock.On("Create", ctx, id, email, passwordHash, createdAt)}
}

func (_c *UserStore_Create_Call) Run(run func(ctx context.Context, id string, email string, passwordHash string, createdAt string)) *UserStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserStore_Create_Call) Return(user *models.User, err error) *UserStore_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserStore_Create_Call) RunAndReturn(run func(ctx context.Context, id string, email string, passwordHash string, createdAt string) (*models.User, error)) *UserStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type UserStore
func (_mock *UserStore) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStore_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserStore_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserStore_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserStore_GetByEmail_Call {
	return &UserStore_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserStore_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserStore_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStore_GetByEmail_Call) Return(user *models.User, err error) *UserStore_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserStore_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *UserStore_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type UserStore
func (_mock *UserStore) GetByID(ctx context.Context, id string) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserStore_Expecter) GetByID(ctx interface{}, id interface{}) *UserStore_GetByID_Call {
	return &UserStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStore_GetByID_Call) Return(user *models.User, err error) *UserStore_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.User, error)) *UserStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
