// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	mock "github.com/stretchr/testify/mock"
)

// NewNeo4jKit creates a new instance of Neo4jKit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNeo4jKit(t interface {
	mock.TestingT
	Cleanup(func())
}) *Neo4jKit {
	mock := &Neo4jKit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Neo4jKit is an autogenerated mock type for the Neo4jKit type
type Neo4jKit struct {
	mock.Mock
}

type Neo4jKit_Expecter struct {
	mock *mock.Mock
}

func (_m *Neo4jKit) EXPECT() *Neo4jKit_Expecter {
	return &Neo4jKit_Expecter{mock: &_m.Mock}
}

// Collect provides a mock function for the type Neo4jKit
func (_mock *Neo4jKit) Collect(ctx context.Context, cypher string, params map[string]any) ([]*neo4j.Record, error) {
	ret := _mock.Called(ctx, cypher, params)

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 []*neo4j.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) ([]*neo4j.Record, error)); ok {
		return returnFunc(ctx, cypher, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) []*neo4j.Record); ok {
		r0 = returnFunc(ctx, cypher, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*neo4j.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, cypher, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Neo4jKit_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type Neo4jKit_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - ctx context.Context
//   - cypher string
//   - params map[string]any
func (_e *Neo4jKit_Expecter) Collect(ctx interface{}, cypher interface{}, params interface{}) *Neo4jKit_Collect_Call {
	return &Neo4jKit_Collect_Call{Call: _e.mock.On("Collect", ctx, cypher, params)}
}

func (_c *Neo4jKit_Collect_Call) Run(run func(ctx context.Context, cypher string, params map[string]any)) *Neo4jKit_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Neo4jKit_Collect_Call) Return(vs []*neo4j.Record, err error) *Neo4jKit_Collect_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Neo4jKit_Collect_Call) RunAndReturn(run func(ctx context.Context, cypher string, params map[string]any) ([]*neo4j.Record, error)) *Neo4jKit_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type Neo4jKit
func (_mock *Neo4jKit) Run(ctx context.Context, cypher string, params map[string]any) error {
	ret := _mock.Called(ctx, cypher, params)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, cypher, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Neo4jKit_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Neo4jKit_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - cypher string
//   - params map[string]any
func (_e *Neo4jKit_Expecter) Run(ctx interface{}, cypher interface{}, params interface{}) *Neo4jKit_Run_Call {
	return &Neo4jKit_Run_Call{Call: _e.mock.On("Run", ctx, cypher, params)}
}

func (_c *Neo4jKit_Run_Call) Run(run func(ctx context.Context, cypher string, params map[string]any)) *Neo4jKit_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Neo4jKit_Run_Call) Return(err error) *Neo4jKit_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Neo4jKit_Run_Call) RunAndReturn(run func(ctx context.Context, cypher string, params map[string]any) error) *Neo4jKit_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Single provides a mock function for the type Neo4jKit
func (_mock *Neo4jKit) Single(ctx context.Context, cypher string, params map[string]any) (*neo4j.Record, error) {
	ret := _mock.Called(ctx, cypher, params)

	if len(ret) == 0 {
		panic("no return value specified for Single")
	}

	var r0 *neo4j.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (*neo4j.Record, error)); ok {
		return returnFunc(ctx, cypher, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) *neo4j.Record); ok {
		r0 = returnFunc(ctx, cypher, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*neo4j.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, cypher, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Neo4jKit_Single_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Single'
type Neo4jKit_Single_Call struct {
	*mock.Call
}

// Single is a helper method to define mock.On call
//   - ctx context.Context
//   - cypher string
//   - params map[string]any
func (_e *Neo4jKit_Expecter) Single(ctx interface{}, cypher interface{}, params interface{}) *Neo4jKit_Single_Call {
	return &Neo4jKit_Single_Call{Call: _e.mock.On("Single", ctx, cypher, params)}
}

func (_c *Neo4jKit_Single_Call) Run(run func(ctx context.Context, cypher string, params map[string]any)) *Neo4jKit_Single_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Neo4jKit_Single_Call) Return(v *neo4j.Record, err error) *Neo4jKit_Single_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Neo4jKit_Single_Call) RunAndReturn(run func(ctx context.Context, cypher string, params map[string]any) (*neo4j.Record, error)) *Neo4jKit_Single_Call {
	_c.Call.Return(run)
	return _c
}
